# Generated by Django 4.1.4 on 2023-05-21 17:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("imagerie", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="group_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
