# Generated by Django 4.1.4 on 2023-05-21 17:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("imagerie", "0002_image_group_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="unique_id",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="group_id",
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False),
        ),
    ]
