# Generated by Django 4.1.4 on 2023-05-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagerie", "0003_image_unique_id_alter_image_group_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="unique_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
