# Generated by Django 4.1.4 on 2023-05-21 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("imagerie", "0005_remove_image_unique_id_alter_image_group_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="group_id",
        ),
    ]
