# Generated by Django 4.1.4 on 2023-05-21 18:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("imagerie", "0006_remove_image_group_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="group_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="image",
            name="unique_id",
            field=models.CharField(default="", max_length=100, unique=True),
        ),
    ]
